In [2]:
#ARRAYS

In [7]:
# Criando uma matriz, array dentro de array
import numpy as np

In [58]:
matriz = np.aray([[1,2,3],[1,2,3]])

AttributeError: module 'numpy' has no attribute 'aray'

In [59]:
matriz = np.array([[1,2,3],[4,5,6]])

In [60]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [61]:
matriz = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [62]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [63]:
# Se listarmos as dimensões da matriz, teremos 3

In [64]:
matriz.shape

(3, 3)

In [65]:
print(matriz.shape)

(3, 3)


In [66]:
# Saída (3, 3) = linhas,colunas


In [67]:
# Criando uma matriz 3x3 apenas com números 1, podemos usar também a função
#zeros vista anteriormente 


In [68]:
matriz1 = np.ones((3,3))

In [69]:
matriz1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
matriz2 = np.zeros(3)

In [71]:
matriz2

array([0., 0., 0.])

In [72]:
martriz3 = np.zeros((3,3))

In [73]:
matriz3

NameError: name 'matriz3' is not defined

In [74]:
martriz3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
# Para saber a quantidade de elementos da matriz usamos a função size

In [76]:
martriz.size

NameError: name 'martriz' is not defined

In [77]:
martriz3.size

9

In [78]:
# Para alterar um elemento da matriz, devemos informar o número da linha e coluna

In [79]:
martriz3[1,0] = 100

In [80]:
print(martriz3)

[[  0.   0.   0.]
 [100.   0.   0.]
 [  0.   0.   0.]]


In [81]:
#Veremos mais algumas funções do Numpy, por exemplo, para manipular valores randômicos e um pouco de estatística. 
#Ressaltamos que as funções apresentadas nesta seção podem ser utilizadas em vetores ou matrizes.

In [1]:
# Usando o método rand() para sortear valores aleatórios

In [3]:
import numpy as np

print(np.random.rand(10))

[0.88270429 0.92351636 0.71977511 0.92621417 0.4382166  0.57013877
 0.42153432 0.79417971 0.53406338 0.77163785]


In [4]:
# Podemos criar uma matriz 4x4 com valores aleatórios

In [5]:
matriz2 = np.random.randn(4,4)

In [6]:
print(matriz2)

[[-1.00520631  0.78399664 -1.44093415  0.38112455]
 [-0.24214998 -1.26636939  0.28159178 -0.06077165]
 [-0.65996329  1.58392051  0.42518441 -1.5279169 ]
 [-0.33537449 -0.4648978   1.50029193  2.14669308]]


In [8]:
#Vamos criar um vetor

In [9]:
v = np.array([10,37,78,100,175])

In [10]:
# A média de uma amostra é o valor que aponta para onde mais se concentram
#os dados, vamos usar a função mean()

In [11]:
np.mean(v)

80.0

In [12]:
# Já o desvio padrão mostra o quanto de variação existe em relação à média.
#Vamos usar o método std()

In [13]:
np.std(v)

56.8823346918883

In [14]:
# A variância de uma variável aleatória é uma medida da sua dispersão indicando
#o quanto os valores estão longe do esperado

In [15]:
np.var(v)

3235.6

In [16]:
# Podemos fazer o somatório dos números do array com sum()

In [17]:
np.sum(v)

400

In [18]:
# Para retornar o produto dos elementos

In [19]:
np.prod(V)

NameError: name 'V' is not defined

In [20]:
np.prod(v)

505050000

In [21]:
# Para criar um conjunto (10x2) de uma distribuição normal usamos randn()

In [22]:
v1 = np.random.randn(10,2)

In [23]:
print(v1)

[[-1.45466509 -1.99968125]
 [-0.55659897 -0.6314242 ]
 [-0.07665824 -1.48656422]
 [ 0.72963002 -2.30186206]
 [ 0.64298385  0.01269328]
 [-1.32988236  0.01856889]
 [-1.90136442 -0.86043082]
 [ 0.84775457  1.69691558]
 [-1.77525013  0.43971944]
 [-1.51851844  3.00853623]]


In [24]:
# Vamos ver algumas funções para fatiamento dos dados

In [25]:
v2 = np.arange(10)

In [26]:
print(v2)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
v2 = np.arange(10,10)

In [28]:
print(v2)

[]


In [29]:
v3 = np.arange(10,10)

In [30]:
print(v3)

[]


In [31]:
v3

array([], dtype=int32)

In [32]:
v2 = np.arange(10)

In [33]:
print(v2)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
# Podemos fatiar o array usando [start:end:step]

In [35]:
v2[1:9:2]

array([1, 3, 5, 7])

In [36]:
print(v2[1:9:2])

[1 3 5 7]


In [37]:
# Os vetores podem ser comparados com “==”, é comparado cada valor

In [38]:
v3 = np.array([2, 2, 3, 1])
v4 = np.array([4, 5, 3, 1])

In [39]:
v3 == v4

array([False, False,  True,  True])

In [40]:
print(v3 == v4)

[False False  True  True]
